version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
     - image: circleci/node:16.13-browsers
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up Docker
          command: |
            echo "Attempting Docker login"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              IMAGE_TAG="production";
            else
              IMAGE_TAG="development";
            fi
            echo "IMAGE_TAG is set to: $IMAGE_TAG"
            docker build -t rifandye/muclone-image-hub:$IMAGE_TAG ./src
      - run:
          name: Push Docker image to Docker Hub
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
                IMAGE_TAG="production";
              else
                IMAGE_TAG="development";
              fi
            echo "Pushing Docker image with tag: rifandye/muclone-image-hub:$IMAGE_TAG"
            docker push rifandye/muclone-image-hub:$IMAGE_TAG
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - main
