version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
     - image: circleci/node:16.13-browsers
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - run:
          name: Set up Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            # Determine the tag based on the branch
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              IMAGE_TAG="production";
            else
              IMAGE_TAG="development";
            fi
            docker build -t rifandye/muclone-image-hub:$IMAGE_TAG ./src

            - run:
          name: Verify Docker Login
          command: docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Confirm Docker Image
          command: docker images | grep rifandye/muclone-image-hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push rifandye/muclone-image-hub:$IMAGE_TAG

  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: SSH to VPS and pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP \<< 'EOF'
              docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_USERNAME"
              docker pull rifandye/muclone-image-hub:development
              docker stop mu-clone-development || true
              docker rm mu-clone-development || true
              docker run -d --name mu-clone-development -p 8001:3001 rifandye/muclone-image-hub:development
            EOF

  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: SSH to VPS and pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP \<< 'EOF'
              docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_USERNAME"
              docker pull rifandye/muclone-image-hub:production
              docker stop mu-clone-production || true
              docker rm mu-clone-production || true
              docker run -d --name mu-clone-production -p 8002:3002 rifandye/muclone-image-hub:production
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - main
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: development
          context: MUClone-Dev-Context  # Move context here
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: main
          context: MUClone-Prod-Context  # Move context here
