version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
     - image: circleci/node:16.13-browsers
    environment:
      IMAGE_TAG: ""
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up Docker
          command: |
            echo "Attempting Docker login"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              IMAGE_TAG="production";
            else
              IMAGE_TAG="development";
            fi
            echo "IMAGE_TAG is set to: $IMAGE_TAG"
            docker build \
              --build-arg PORT=$PORT \
              --build-arg NODE_ENV=$IMAGE_TAG \
              --build-arg DB_USERNAME=$DB_USERNAME \
              --build-arg DB_PASSWORD=$DB_PASSWORD \
              --build-arg DB_NAME=$DB_NAME \
              --build-arg DB_HOST=$DB_HOST \
              --build-arg JWT_SECRET=$JWT_SECRET \
              --build-arg ALLOWED_ORIGINS=$ALLOWED_ORIGINS \
              -t rifandye/muclone-image-hub:$IMAGE_TAG ./src
      - run:
          name: Push Docker image to Docker Hub
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
                IMAGE_TAG="production";
              else
                IMAGE_TAG="development";
              fi
            echo "Pushing Docker image with tag: rifandye/muclone-image-hub:$IMAGE_TAG"
            docker push rifandye/muclone-image-hub:$IMAGE_TAG
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: SSH to VPS and pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no -p $VPS_PORT $VPS_USER@$VPS_IP \<< 'EOF'
              docker pull rifandye/muclone-image-hub:development
              docker ps -a --filter "name=mu-clone-development" -q | grep -q . && \
              docker stop mu-clone-development && docker rm mu-clone-development || true
              docker run -d --name mu-clone-development --network Runestone-Network -p 8001:3001 rifandye/muclone-image-hub:development
            EOF

  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: SSH to VPS and pull Docker image
          command: |
            ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP \<< 'EOF'
              docker pull rifandye/muclone-image-hub:production
              docker stop mu-clone-production || true
              docker rm mu-clone-production || true
              docker run -d --name mu-clone-production -p 8002:3002 rifandye/muclone-image-hub:production
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - main
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: development
          context: MUClone-Dev-Context 
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: main
          context: MUClone-Prod-Context 
